services:
  httpd:
    image: httpd
    ports:
      - 6001:80

  nginx:
    image: nginx
    ports:
      - 6002:80

  tomcat:
    image: tomcat
    ports:
      - 6003:8080

  golang:
    build:
      context: servers/go
    ports:
      - 6004:80

  python:
    image: python
    ports:
      - 6005:8000
    command: python -m http.server
    init: true
